// auto-generated by comb/rtl/emit_routers.hexa — degree-4 mesh router stub
module router_d4 #(parameter W = 64) (
    input  wire           clk, rst,
    // 4 input ports: N, S, E, W
    input  wire [W-1:0]   in_n, in_s, in_e, in_w,
    input  wire           iv_n, iv_s, iv_e, iv_w,
    output wire           ir_n, ir_s, ir_e, ir_w,
    // 4 output ports (same axes)
    output reg  [W-1:0]   out_n, out_s, out_e, out_w,
    output reg            ov_n, ov_s, ov_e, ov_w,
    input  wire           or_n, or_s, or_e, or_w
);
    // XY dimension-order routing; round-robin arbiter
    // (datapath omitted in stub — see hexa-arch[chip] absorption)
endmodule

// auto-generated by comb/rtl/emit_routers.hexa — degree-6 hex router stub
module router_d6 #(parameter W = 64) (
    input  wire           clk, rst,
    // 6 input ports on hex axial axes:
    //   pos_q = (+1,  0)   neg_q = (-1,  0)
    //   pos_r = ( 0, +1)   neg_r = ( 0, -1)
    //   pos_s = (+1, -1)   neg_s = (-1, +1)
    input  wire [W-1:0]   in_pq, in_nq, in_pr, in_nr, in_ps, in_ns,
    input  wire           iv_pq, iv_nq, iv_pr, iv_nr, iv_ps, iv_ns,
    output wire           ir_pq, ir_nq, ir_pr, ir_nr, ir_ps, ir_ns,
    // 6 output ports
    output reg  [W-1:0]   out_pq, out_nq, out_pr, out_nr, out_ps, out_ns,
    output reg            ov_pq, ov_nq, ov_pr, ov_nr, ov_ps, ov_ns,
    input  wire           or_pq, or_nq, or_pr, or_nr, or_ps, or_ns
);
    // hex dimension-order routing on axial (q,r,s=-q-r);
    // 6-input round-robin arbiter (port cost ~1.5x of d4)
    // (datapath omitted in stub — see hexa-arch[chip] absorption)
endmodule

