// Generated by HEXA self-host compiler
#include "runtime.h"

HexaVal S(HexaVal buf);
HexaVal u_main(void);




HexaVal S(HexaVal buf) {
    static const char* const _k[] = {"buf"};
    HexaVal _v[] = {buf};
    return hexa_struct_pack_map("S", 1, _k, _v);
}


HexaVal u_main(void) {
    __hexa_fn_arena_enter();
    HexaVal s = S(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_int(1)), hexa_int(2)), hexa_int(3)), hexa_int(4)));
    hexa_println(hexa_int(42));
    return __hexa_fn_arena_return(hexa_void());
}


int main(int argc, char** argv) {
    setvbuf(stdout, NULL, _IOLBF, 0);
    setvbuf(stderr, NULL, _IOLBF, 0);
    hexa_set_args(argc, argv);
    u_main();
    fflush(stdout); fflush(stderr);
    return 0;
}
