#!/usr/bin/env bash
# hexa-cuda dojo run glue — generated by stdlib/dojo/hexa_cuda
# slug: tiled-gemm  ·  kata: tiled-gemm
set -euo pipefail
cd "$(dirname "$0")"

# ── $0 gate — parse-check the kernel (no GPU, no nvcc needed) ──
# The @gpu_kernel fixture is parse-clean today (gpu/SPEC.md §2). This
# is the machine-independent kata gate — it catches every intrinsic
# / syntax error without a GPU.
echo "hexa-cuda: parse-check kernel.hexa"
hexa parse kernel.hexa

# ── build → NVPTX (needs a CUDA toolchain; RFC 055-P3 lowering) ──
# hexa partitions @gpu_* fns to the NVPTX codegen target and emits
# cubin-ready PTX; the host glue stays CPU-native. ptxas (PTX→SASS)
# is an external NVIDIA tool — the hexa→PTX TEXT path is LLVM-free.
if command -v ptxas >/dev/null 2>&1; then
    echo "hexa-cuda: build --target=nvptx kernel.hexa"
    hexa build --target=nvptx kernel.hexa
else
    echo "hexa-cuda: ptxas not found — parse gate only (NVPTX build needs a CUDA host)"
fi
