#!/usr/bin/env bash
# tests/integration/run_all.sh — stage1 integration test driver
#
# Seeded under hxa-20260424-005 item #10 (integration test suite seed).
# Walks tests/integration/<nn>_*/test.sh, runs each with timeout 60s, records
# PASS/FAIL/SKIP, exits non-zero if any test fails.
#
# Expected failures (until agent A hxa-20260424-005 #1/#3 lands):
#   06_exec_argv_no_shell_expansion
#   07_json_parse_roundtrip
#
# HEXA_BIN defaults to $HEXA_ROOT/hexa — a local bash shim that exec's
# hexa.real directly. This intentionally bypasses ~/.hx/bin/hexa (the
# fleet load-balancer wrapper that auto-routes `hexa run|batch` to
# remote ubu-N hosts), keeping integration tests mac-local and
# deterministic. Override HEXA_BIN only if you need a different
# interpreter; never point it at ~/.hx/bin/hexa.

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
HEXA_ROOT="$(cd "$HERE/../.." && pwd)"
export HEXA_BIN="${HEXA_BIN:-$HEXA_ROOT/hexa}"
export HEXA_ROOT
export FIXTURES="$HERE/fixtures"

if [ ! -x "$HEXA_BIN" ]; then
    echo "run_all: HEXA_BIN not executable at $HEXA_BIN" >&2
    exit 2
fi

# Portable timeout: macOS has neither GNU `timeout` nor Homebrew `gtimeout`
# by default. Prefer them when present; otherwise fall back to a perl-based
# alarm wrapper (perl ships with macOS base system). Exit code 124 is
# preserved for timeout-kill so the existing `rc -eq 124` branch still fires.
#
# To make this fix transparent to individual test.sh scripts (some of which
# call `timeout` themselves — e.g. 08_roadmap_schema_adapter_anima_fixture),
# we materialize a `timeout` shim under a private bindir and prepend it to
# PATH for the duration of run_all.sh. The shim resolves to the real binary
# when available, else gtimeout, else perl-alarm.
if command -v gtimeout >/dev/null 2>&1; then
    TIMEOUT_CMD=(gtimeout)
elif command -v timeout >/dev/null 2>&1; then
    TIMEOUT_CMD=(timeout)
elif command -v perl >/dev/null 2>&1; then
    TIMEOUT_CMD=(perl -e '
        my $sec = shift;
        my $pid = fork();
        die "fork: $!" unless defined $pid;
        if ($pid == 0) { exec @ARGV; die "exec: $!"; }
        local $SIG{ALRM} = sub {
            kill "TERM", $pid;
            sleep 1;
            kill "KILL", $pid;
            exit 124;
        };
        alarm $sec;
        waitpid($pid, 0);
        my $rc = $?;
        alarm 0;
        exit ($rc >> 8) if ($rc & 0xff) == 0;
        exit 128 + ($rc & 0x7f);
    ' --)
else
    echo "run_all: no timeout/gtimeout/perl available; aborting" >&2
    exit 2
fi

# Materialize a `timeout` shim on PATH so child test.sh scripts that invoke
# `timeout` directly also get the fallback. No-op when GNU timeout already
# exists on PATH (we still install the shim, but it dispatches to the same
# resolver, which will pick the real binary).
_SHIM_BIN="$(mktemp -d -t hxa_intg_bin_XXXXXX)"
trap 'rm -rf "$_SHIM_BIN"' EXIT
cat > "$_SHIM_BIN/timeout" <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by tests/integration/run_all.sh — macOS-portable timeout.
if command -v gtimeout >/dev/null 2>&1; then
    exec gtimeout "$@"
fi
# Avoid recursing into self: walk PATH and pick a `timeout` that isn't us.
_self="$(command -v timeout)"
IFS=: read -r -a _parts <<<"$PATH"
for _p in "${_parts[@]}"; do
    [ -x "$_p/timeout" ] || continue
    if [ "$_p/timeout" != "$_self" ]; then
        exec "$_p/timeout" "$@"
    fi
done
# Fallback: perl alarm. Strip GNU-style `--preserve-status`, `--kill-after=`,
# and `--signal=` if they appear; we don't honor them but tolerate them.
_sec=""
while [ $# -gt 0 ]; do
    case "$1" in
        --preserve-status|-k) shift; continue ;;
        --kill-after=*|--signal=*) shift; continue ;;
        -s) shift 2; continue ;;
        --) shift; break ;;
        -*) shift; continue ;;
        *) _sec="$1"; shift; break ;;
    esac
done
exec perl -e '
    my $sec = shift;
    my $pid = fork();
    die "fork: $!" unless defined $pid;
    if ($pid == 0) { exec @ARGV; die "exec: $!"; }
    local $SIG{ALRM} = sub {
        kill "TERM", $pid;
        sleep 1;
        kill "KILL", $pid;
        exit 124;
    };
    alarm $sec;
    waitpid($pid, 0);
    my $rc = $?;
    alarm 0;
    exit ($rc >> 8) if ($rc & 0xff) == 0;
    exit 128 + ($rc & 0x7f);
' -- "$_sec" "$@"
SHIM
chmod +x "$_SHIM_BIN/timeout"
export PATH="$_SHIM_BIN:$PATH"

pass=0
fail=0
skip=0
failed_tests=()

# Iterate in numeric order (01_.., 02_..).
for d in "$HERE"/[0-9][0-9]_*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    script="$d/test.sh"
    if [ ! -x "$script" ]; then
        echo "[SKIP] $name — test.sh missing or not executable"
        skip=$((skip + 1))
        continue
    fi
    printf '[ RUN] %-55s ' "$name"
    out="$("${TIMEOUT_CMD[@]}" 60 bash "$script" 2>&1)"
    rc=$?
    if [ $rc -eq 0 ]; then
        echo "PASS"
        pass=$((pass + 1))
    elif [ $rc -eq 77 ]; then
        # 77 reserved for self-skip (agent A dependencies etc.)
        echo "SKIP"
        skip=$((skip + 1))
    elif [ $rc -eq 124 ]; then
        echo "FAIL (timeout 60s)"
        fail=$((fail + 1))
        failed_tests+=("$name (timeout)")
        echo "---- $name output (last 20 lines) ----"
        echo "$out" | tail -20
        echo "---------------------------------------"
    else
        echo "FAIL (rc=$rc)"
        fail=$((fail + 1))
        failed_tests+=("$name (rc=$rc)")
        echo "---- $name output (last 20 lines) ----"
        echo "$out" | tail -20
        echo "---------------------------------------"
    fi
done

total=$((pass + fail + skip))
echo ""
echo "==================================================="
echo "integration summary: total=$total passed=$pass failed=$fail skipped=$skip"
if [ $fail -gt 0 ]; then
    echo "failed tests:"
    for t in "${failed_tests[@]}"; do
        echo "  - $t"
    done
    echo "==================================================="
    exit 1
fi
echo "==================================================="
exit 0
