#!/usr/bin/env python3
"""BLOWUP-PCF-VERIFIED — revisit the blowup engine, wired to the verified PCF gate (not proxies).

Two prior discovery-engine families were measured CLOSED:
  · blowup (smash 9-phase, compiler/smash/phases.hexa) produced FREE-FORM structural scaffolds but
    as seed-hash PROXIES they were unverifiable; blowup_llm_expanded_grammar_probe.py (#4137) found
    0 genuine survivors in the arithmetic-congruence space (Ono-closed).
  · emergence (math_emergence_engine.py #4139) GENERATED byte-emergence relations but the numerology
    null-model showed they are n=6 coincidence (숫자시), not structure — 0 promoted.
Both ran in the CLOSED arithmetic space. The PCF campaign (#4144/48/50/52) then built a VERIFIED gate
(LLL/Möbius integer-relation detection) over the OPEN constant-PCF frontier.

This revisit applies the NEXUS principle "candidate ≠ discovery": it re-points blowup's STRUCTURAL
operators at PCF structures (a(n),b(n) polynomials) and gates EVERY mutant through the verified LLL
detector — so blowup stops emitting unverifiable proxies and starts emitting detector-checked
candidates. The honest question: does blowup-structural-mutation of KNOWN seed PCFs surface a NEW
verified relation, or only re-derive the seed's own (classical) class?

blowup operators (from smash/phases.hexa, reference-mapped to PCF structure):
  P2 ouroboros-mutate : perturb each polynomial coefficient by ±1,±2
  P4 corollary-expand : scale a(n) by a small constant; shift b0
  P8 wave-propagate   : index shift  a(n)→a(n+1), b(n)→b(n+1)
  P5 telescope        : multiply a(n) by n (or n²)
Each mutant's convergent limit is fed to the degree-2 LLL detector vs a constant set; classical
(Apéry/Gauss/Euler) are reference-matched out; a non-catalogued survivor is 🟧 novel.

c2 honest: a relation = ∀-term UNPROVEN conjecture. Deterministic, exact convergents, stdlib. LOCAL.
"""
import sys
from fractions import Fraction
from decimal import Decimal, getcontext
getcontext().prec = 80

PI    = Decimal("3.14159265358979323846264338327950288419716939937510582097494459230781640628620899")
ZETA3 = Decimal("1.20205690315959428539973816151144999076498629234049888179227155534183820578631309")
ZETA2 = PI*PI/Decimal(6)
CAT   = Decimal("0.91596559417721901505460351493238411077414937428167213426649811962176301977625476")
LN2   = Decimal("0.69314718055994530941723212145817656807550013436025525412068000949339362196969471")
PHI   = Decimal("1.61803398874989484820458683436563811772030917980576286213544862270526046281890244")
SQRT2 = Decimal("1.41421356237309504880168872420969807856967187537694807317667973799073247846210703")
CONSTS = {"zeta(2)":ZETA2,"zeta(3)":ZETA3,"Catalan":CAT,"pi":PI,"ln2":LN2}

# ---- float LLL + exact verify (same canonical detector as the PSLQ-3 probe) ----
def _fdot(u,v): return sum(a*b for a,b in zip(u,v))
def lll_float(basis, delta=0.75):
    B=[[float(x) for x in r] for r in basis]; Bi=[[int(x) for x in r] for r in basis]; n=len(B)
    def gs():
        Bs=[None]*n; mu=[[0.0]*n for _ in range(n)]
        for i in range(n):
            Bs[i]=list(B[i])
            for j in range(i):
                dj=_fdot(Bs[j],Bs[j]); mu[i][j]=_fdot(B[i],Bs[j])/dj if dj else 0.0
                Bs[i]=[a-mu[i][j]*b for a,b in zip(Bs[i],Bs[j])]
        return Bs,mu
    Bs,mu=gs(); k=1; g=0
    while k<n:
        g+=1
        if g>5000: break
        for j in range(k-1,-1,-1):
            if abs(mu[k][j])>0.5:
                q=round(mu[k][j]); B[k]=[a-q*b for a,b in zip(B[k],B[j])]; Bi[k]=[a-q*b for a,b in zip(Bi[k],Bi[j])]; Bs,mu=gs()
        if _fdot(Bs[k],Bs[k])>=(delta-mu[k][k-1]**2)*_fdot(Bs[k-1],Bs[k-1]): k+=1
        else:
            B[k],B[k-1]=B[k-1],B[k]; Bi[k],Bi[k-1]=Bi[k-1],Bi[k]; Bs,mu=gs(); k=max(k-1,1)
    return Bi
def find_relation(reals, scale_digits=15, max_coef=10**5, verify_dig=44):
    n=len(reals); K=10**scale_digits; basis=[]
    for i in range(n):
        row=[1 if j==i else 0 for j in range(n)]; row.append(int((reals[i]*K).to_integral_value(rounding="ROUND_HALF_EVEN"))); basis.append(row)
    red=lll_float(basis); eps=Decimal(10)**(-verify_dig)
    for row in red:
        rel=row[:n]
        if not any(rel) or any(abs(x)>max_coef for x in rel): continue
        s=sum((Decimal(rel[i])*reals[i] for i in range(n)),Decimal(0))
        if abs(s)<eps: return rel
    return None

def polyval(c,n):
    r=0
    for x in reversed(c): r=r*n+x
    return r
def pcf_limit(ac,bc,kmax=120):
    b0=polyval(bc,0); p0,p1=Fraction(1),Fraction(b0); q0,q1=Fraction(0),Fraction(1); prev=None; eps=Decimal(10)**-46; st=0
    for n in range(1,kmax+1):
        an=polyval(ac,n); bn=polyval(bc,n); p0,p1=p1,bn*p1+an*p0; q0,q1=q1,bn*q1+an*q0
        if q1==0: return None
        if n>=4 and (n%2==0 or n>30):
            cur=Decimal(p1.numerator*q1.denominator)/Decimal(p1.denominator*q1.numerator)
            if prev is not None:
                d=abs(cur-prev)
                if d<eps:
                    st+=1
                    if st>=2: return cur
                else: st=0
                if n>45 and d>Decimal(10)**-6: return None
            prev=cur
    return None
def detect(L):
    for cn,c in CONSTS.items():
        r=find_relation([Decimal(1),c,c*c,L,c*L,c*c*L])
        if r is not None and any(r[3:]):
            kind="mobius" if (r[2]==0 and r[5]==0) else "algebraic2"
            return (cn,r,kind)
    return None

# ---- seed PCFs (known) ----
SEEDS = {
    "Apery-z3":   ([0,0,0,0,0,0,-1], [5,27,51,34]),   # → 6/ζ(3)
    "vdP-z2":     ([0,0,0,0,1],      [3,11,11]),       # → 5/ζ(2)
    "Euler-e":    ([0,-1],           [3,1]),           # → e (a=-n, b=n+3)
    "Brouncker":  ([1,-4,4],         [1,2]),           # 4/π regime (a=(2n-1)², b≈2)
}

# ---- blowup structural operators on (a, b) ----
def blowup_mutants(ac, bc):
    """yield (label, a, b) structural mutants per smash phases P2/P4/P5/P8."""
    out = []
    # P2 ouroboros-mutate: perturb each coef by ±1, ±2
    for vi, vec in (("a",ac),("b",bc)):
        for i in range(len(vec)):
            for d in (-2,-1,1,2):
                m = list(vec); m[i]+=d
                if vi=="a": out.append((f"P2-mutate-a{i}{d:+d}", m, list(bc)))
                else:       out.append((f"P2-mutate-b{i}{d:+d}", list(ac), m))
    # P4 corollary-expand: scale a by k, shift b0 by k
    for k in (-2,-1,2,3):
        out.append((f"P4-scaleA*{k}", [x*k for x in ac], list(bc)))
        b=list(bc); b[0]+=k; out.append((f"P4-shiftB0{k:+d}", list(ac), b))
    # P5 telescope: a(n)·n (raise a-degree by 1) and a(n)·n²
    out.append(("P5-telescope-n",  [0]+list(ac), list(bc)))
    out.append(("P5-telescope-n2", [0,0]+list(ac), list(bc)))
    # P8 wave-propagate: index shift a(n)->a(n+1), b(n)->b(n+1) via binomial expansion
    def shift(poly):
        # poly(n+1): expand. degree<=6 manual binomial
        from math import comb
        d=len(poly)-1; res=[0]*(d+1)
        for i,ci in enumerate(poly):
            for j in range(i+1):
                res[j]+=ci*comb(i,j)
        return res
    out.append(("P8-wave-shift", shift(ac), shift(bc)))
    return out

def main():
    print("=== BLOWUP-PCF-VERIFIED — blowup operators × verified LLL gate ===\n")
    # sanity
    rphi=find_relation([Decimal(1),PHI,PHI*PHI]); rap=find_relation([Decimal(1),ZETA3,ZETA3*(Decimal(6)/ZETA3)])
    print(f"--- detector sanity: φ={rphi} Apéry={rap} → {'PASS' if rphi and rap else 'FAIL'}\n")
    if not (rphi and rap): print("ABORT (tool-first)"); return

    all_hits=[]; tried=0
    for sname,(ac,bc) in SEEDS.items():
        L0=pcf_limit(ac,bc); d0=detect(L0) if L0 else None
        print(f"--- seed {sname}: a={ac} b={bc} → L={str(L0)[:20] if L0 else 'None'} · seed-detect={d0[0]+'/'+d0[2] if d0 else 'none'}")
        muts=blowup_mutants(ac,bc)
        sh=0
        for lbl,ma,mb in muts:
            tried+=1
            L=pcf_limit(ma,mb)
            if L is None: continue
            det=detect(L)
            if det:
                cn,rel,kind=det
                all_hits.append((sname,lbl,ma,mb,cn,rel,kind,str(L)[:20])); sh+=1
        print(f"    blowup mutants={len(muts)} · verified-gate hits={sh}")

    # reference-match: which hits are NEW (not the seed's own class / not Apéry/Gauss)
    print(f"\n--- search: {tried} blowup mutants gated · raw verified hits={len(all_hits)} ---")
    def classical(ma,mb,cn,rel,kind):
        a=list(ma); b=list(mb)
        while len(b)>1 and b[-1]==0: b.pop()
        while len(a)>1 and a[-1]==0: a.pop()
        if kind!="mobius": return False  # any algebraic2 = candidate
        if a==[0,0,0,0,0,0,-1] and b==[5,27,51,34]: return True
        if (len(a)-1)<=2 and (len(b)-1)<=1 and cn in ("pi","ln2"): return True
        if (len(a)-1)<=1 and (len(b)-1)<=1: return True
        return True  # other mobius = MITM-class, not new
    cand=[]; classical_n=0; seen=set()
    for sname,lbl,ma,mb,cn,rel,kind,Ls in all_hits:
        key=(tuple(ma),tuple(mb),cn,tuple(rel))
        if key in seen: continue
        seen.add(key)
        if classical(ma,mb,cn,rel,kind): classical_n+=1
        else: cand.append((sname,lbl,ma,mb,cn,rel,kind,Ls))
    print(f"\n=== REFERENCE-MATCH ===")
    print(f"distinct verified hits={len(seen)} · classical/mobius={classical_n} · 🟧candidate(algebraic2)={len(cand)}")
    for sname,lbl,ma,mb,cn,rel,kind,Ls in cand[:40]:
        print(f"  🟧 [{sname}|{lbl}] {cn}[{kind}] a={ma} b={mb} L={Ls} rel={rel}")
    print(f"\n=== VERDICT ===")
    print(f"BLOWUP_MUTANTS_GATED={tried} · VERIFIED_HITS={len(seen)} · CLASSICAL={classical_n} · CANDIDATES={len(cand)}")
    if cand:
        print(f"→ {len(cand)} 🟧 blowup-derived candidate(s): blowup structural mutation + verified gate")
        print(f"  surfaced a non-seed-class relation. High-prec re-verify + RM-DB. (blowup now PRODUCTIVE")
        print(f"  because wired to a VERIFIED gate, not return-only proxies.)")
    else:
        print(f"→ 0 novel: blowup mutation of known seeds re-derives only the seed's classical class")
        print(f"  through the verified gate. The synthesis (blowup generator + LLL gate) WORKS — it")
        print(f"  correctly gates out unverified proxies — but local structural mutation of catalogued")
        print(f"  PCFs stays in the catalogued class. Genuine novel still needs the pool wide-sweep")
        print(f"  (non-local coefficient band), NOT local blowup mutation. Honest, c2.")
    print(f"REVISIT verdict: blowup·emergence were CLOSED in the arithmetic space; re-pointed at the PCF")
    print(f"frontier WITH the verified gate, blowup is now a legitimate gated generator (proxy→verified).")

main()

# ============================================================================
# MEASURED VERDICT (2026-06-28, mini stdlib, exit 0):
#   detector sanity PASS (φ, Apéry). 4 seed PCFs (Apéry ζ(3), vdP ζ(2), Euler e, Brouncker 4/π),
#   156 blowup structural mutants (P2 mutate / P4 expand / P5 telescope / P8 wave), each gated
#   through the verified degree-2 LLL detector. 25 distinct verified hits — ALL classical/Möbius
#   (mutants of Apéry land on ζ(3)-class relations, etc.). CANDIDATES = 0.
#   blowup·emergence REVISIT verdict (the deliverable):
#     · Both families were measured CLOSED in the arithmetic-congruence space (blowup #4137
#       Ono-closed; emergence #4139 numerology null-model). The PCF campaign built a VERIFIED gate
#       (LLL/Möbius). This revisit WIRES blowup's structural operators THROUGH that gate over the
#       OPEN PCF frontier — so blowup is upgraded from "return-only unverifiable proxy" to a
#       legitimate detector-gated generator (NEXUS principle: candidate ≠ discovery). That upgrade
#       IS the win, independent of novel count.
#     · The LLL verified gate also supersedes emergence's numerology null-model as the principled
#       discriminator: under it, 0 "emergent" relation survives as non-classical in the mini-band.
#     · HONEST limit: LOCAL structural mutation of catalogued seed PCFs stays in the catalogued
#       class (0 novel). Genuine novel needs NON-LOCAL coefficient exploration = the pool wide-sweep
#       (pcf_pool_widesweep on summer), NOT local blowup mutation. Wall = investment/breadth, OPEN.
#   c2 honest. Bounds LOGGED.
# ============================================================================
