#!/bin/bash
# dispatch_r055_p1_vec_add.sh — RFC 055 055-P1 hexa-native vec-add fire.
#
# Fires the 055-P1 hand-emitted PTX (compiler/codegen/nvptx_target.hexa
# `emit_ptx_vec_add_module`) on a vast.ai sm_80+ instance and asserts the
# pre-registered 055-P1 falsifier battery (RFC 055 §7):
#
#   F-RFC055-PTX-EMIT     — `ptxas` accepts the emitted PTX and produces
#                           a cubin without error.
#   F-RFC055-NUMERIC-EQ   — kernel output is byte-equal to the CPU
#                           hexa reference (vec-add reduces nothing →
#                           `max|Δ| == 0`, not a tolerance gate).
#   F-RFC055-LAUNCH-ABI   — host→kernel→host round-trip succeeds via
#                           the Driver-API path (cuModuleLoadData →
#                           cuModuleGetFunction → cuLaunchKernel →
#                           cuCtxSynchronize). The 055-P1 harness
#                           exercises the same call sequence
#                           `_hx_cuda_launch_kernel` will perform when
#                           the hexa `gpu_launch` lowering lands.
#   F-RFC055-NO-LLVM      — the build-graph audit (build.log) shows
#                           the hexa→PTX path links only `cuda` /
#                           `nvptx`/`ptxas` family — no LLVM linkage.
#                           PASS = grep for "LLVM" returns nothing.
#
# This script:
#   (a) generates the PTX TEXT from the hexa NVPTX target by running
#       `hexa run compiler/codegen/nvptx_vec_add_test.hexa --print-ptx`
#       on the local host (the emit pass is pure — no GPU needed);
#   (b) uploads PTX + a thin C harness (state/.../host_vec_add.c) to a
#       vast.ai sm_80+ pod, ptxas-assembles to cubin, dlopen-loads via
#       Driver API, fires the kernel, byte-eq compares to CPU reference;
#   (c) emits result.json with the four falsifier verdicts.
#
# Output: state/rfc055_p1_2026_05_19/{ptx,cubin,result.json,build.log,fire.log}
# Budget: ~$0.50-1.50 (one short fire — single kernel, n=1024, ~10s GPU).
#
# Env: SAVE_POD=1 keeps the instance; VAST_BAD_OFFERS="id,id" blacklists.
#
# NOTE: This script is the *fire harness only* — the parent runs it
# after merging the 055-P1 SSOT changes. The hexa-side PTX emit is
# already validated locally by `nvptx_vec_add_test.hexa`
# (text-shape only); the GPU-side falsifiers above need a real GPU.

set -uo pipefail

REPO="/Users/ghost/core/hexa-lang"
LOCAL_DIR="$REPO/state/rfc055_p1_2026_05_19"
LABEL="hexa-rfc055-p1-vec-add"
REMOTE_WORK="/workspace/rfc055_p1"

# Local artifacts — generated by the parent before fire.
PTX_OUT="$LOCAL_DIR/vec_add.ptx"
HARNESS_C="$LOCAL_DIR/host_vec_add.c"
DISPATCH_LOG="$LOCAL_DIR/dispatch.log"

RUNPOD_SSH_KEY="${HOME}/.runpod/ssh/RunPod-Key-Go"
RUNPODCTL="/opt/homebrew/Cellar/runpodctl/2.1.9/bin/runpodctl"
export RUNPOD_API_KEY="$(secret get runpod.api_key 2>/dev/null)"
GPU_ID="${GPU_ID:-NVIDIA A100-SXM4-80GB}"
# runpod-prebuilt image: sshd pre-configured, CUDA 12.4 toolkit, fast boot.
IMAGE="${IMAGE:-runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04}"
[ -x "$RUNPODCTL" ]      || { echo "ERROR: runpodctl not found at $RUNPODCTL"; exit 1; }
[ -f "$RUNPOD_SSH_KEY" ] || { echo "ERROR: runpod ssh key missing"; exit 1; }
[ -n "$RUNPOD_API_KEY" ] || { echo "ERROR: RUNPOD_API_KEY empty"; exit 1; }

mkdir -p "$LOCAL_DIR"

# ── 0) Generate the PTX text locally via the hexa emit pass. ─────────
#
# Uses HEXA_RUN_NATIVE if available — falls back to the hexa CLI.
# (The emit pass is pure hexa, no GPU touch, no ptxas — pure
# text generation. F-RFC055-NO-LLVM: the hexa step has zero LLVM
# linkage by construction.)
echo "[0/8] Generate PTX text via hexa NVPTX emit pass ..."
HEXA_BIN="${HEXA_BIN:-/Users/ghost/.hx/bin/hexa_real}"
[ -x "$HEXA_BIN" ] || { echo "ERROR: $HEXA_BIN missing"; exit 1; }

# Build a one-shot driver that calls emit_ptx_vec_add_module and prints
# it to stdout. We materialise it inline (no new tracked file).
PTX_DRIVER="$LOCAL_DIR/_emit_driver.hexa"
cat > "$PTX_DRIVER" <<'EMIT_HEXA'
import "../../compiler/codegen/nvptx_target.hexa"
import "../../compiler/codegen/nvptx_ptx_ops.hexa"

fn main() {
    let ptx = emit_ptx_vec_add_module(NVPTX_TARGET_SM80)
    println(ptx)
}
EMIT_HEXA

# Materialise PTX to disk. We use `hexa run` since the emit pass is a
# pure compile-time text walk; no GPU side-effects.
"$HEXA_BIN" run "$PTX_DRIVER" 2>&1 | tee "$PTX_OUT.full.log" \
    | grep -v '^hexa-' | grep -v '^=' > "$PTX_OUT" || true

# A `.visible .entry vadd` marker should be in the file — if not, the
# emit pass failed and we abort before incurring GPU cost.
if ! grep -q ".visible .entry vadd" "$PTX_OUT"; then
    echo "ERROR: PTX emit failed — no `.visible .entry vadd` in output"
    head -40 "$PTX_OUT.full.log"
    exit 1
fi
echo "  PTX text generated: $(wc -l < $PTX_OUT) lines, $(wc -c < $PTX_OUT) bytes"

# ── 0b) Synthesize the host harness (single-TU C program). ───────────
#
# The harness uses CUDA Driver API + `cuModuleLoad`/`cuLaunchKernel` —
# the same sequence `_hx_cuda_launch_kernel` (self/cuda/runtime_cuda.c)
# performs. Vec-add over n=1024, byte-eq vs `c_ref[i] = a[i] + b[i]`.
cat > "$HARNESS_C" <<'HARNESS_C'
/* RFC 055 055-P1 host harness — load hand-emitted vec-add cubin via
 * Driver API, fire kernel on n=1024 [f64] inputs, byte-eq compare to
 * the CPU reference. Mirrors `_hx_cuda_launch_kernel` shape. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <cuda.h>

#define N 1024
#define BLOCK 256

static const char* cu_err(CUresult cr) {
    const char* s = NULL;
    cuGetErrorString(cr, &s);
    return s ? s : "(no message)";
}

int main(int argc, char** argv) {
    const char* cubin_path = (argc > 1) ? argv[1] : "vec_add.cubin";
    /* Read cubin into memory. */
    FILE* f = fopen(cubin_path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", cubin_path); return 2; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    void* blob = malloc(sz);
    if (fread(blob, 1, sz, f) != (size_t)sz) { fprintf(stderr, "short read\n"); return 2; }
    fclose(f);

    CUresult cr;
    cr = cuInit(0);          if (cr != CUDA_SUCCESS) { fprintf(stderr, "cuInit: %s\n", cu_err(cr)); return 3; }
    CUdevice dev;
    cr = cuDeviceGet(&dev, 0); if (cr != CUDA_SUCCESS) { fprintf(stderr, "cuDeviceGet: %s\n", cu_err(cr)); return 3; }
    CUcontext ctx;
    cr = cuCtxCreate(&ctx, 0, dev); if (cr != CUDA_SUCCESS) { fprintf(stderr, "cuCtxCreate: %s\n", cu_err(cr)); return 3; }

    CUmodule mod;
    cr = cuModuleLoadData(&mod, blob);
    if (cr != CUDA_SUCCESS) { fprintf(stderr, "F-RFC055-PTX-EMIT FAIL: cuModuleLoadData: %s\n", cu_err(cr)); return 4; }
    fprintf(stderr, "F-RFC055-PTX-EMIT PASS — cubin loaded\n");

    CUfunction kfn;
    cr = cuModuleGetFunction(&kfn, mod, "vadd");
    if (cr != CUDA_SUCCESS) { fprintf(stderr, "cuModuleGetFunction(vadd): %s\n", cu_err(cr)); return 4; }

    /* Allocate + populate inputs. */
    double *a_h = malloc(N*sizeof(double));
    double *b_h = malloc(N*sizeof(double));
    double *c_h = calloc(N, sizeof(double));
    double *c_ref = malloc(N*sizeof(double));
    for (int i = 0; i < N; i++) {
        a_h[i] = (double)i;
        b_h[i] = (double)(N - i);
        c_ref[i] = a_h[i] + b_h[i];
    }

    CUdeviceptr a_d, b_d, c_d;
    cuMemAlloc(&a_d, N*sizeof(double));
    cuMemAlloc(&b_d, N*sizeof(double));
    cuMemAlloc(&c_d, N*sizeof(double));
    cuMemcpyHtoD(a_d, a_h, N*sizeof(double));
    cuMemcpyHtoD(b_d, b_h, N*sizeof(double));
    cuMemcpyHtoD(c_d, c_h, N*sizeof(double));

    /* Launch — F-RFC055-LAUNCH-ABI. */
    int64_t n_arg = N;
    void* args[] = { &a_d, &b_d, &c_d, &n_arg };
    int grid_x = (N + BLOCK - 1) / BLOCK;
    cr = cuLaunchKernel(kfn, grid_x, 1, 1, BLOCK, 1, 1, 0, NULL, args, NULL);
    if (cr != CUDA_SUCCESS) { fprintf(stderr, "F-RFC055-LAUNCH-ABI FAIL: cuLaunchKernel: %s\n", cu_err(cr)); return 5; }
    cr = cuCtxSynchronize();
    if (cr != CUDA_SUCCESS) { fprintf(stderr, "cuCtxSynchronize: %s\n", cu_err(cr)); return 5; }
    fprintf(stderr, "F-RFC055-LAUNCH-ABI PASS — host→kernel→host\n");

    cuMemcpyDtoH(c_h, c_d, N*sizeof(double));

    /* F-RFC055-NUMERIC-EQ — byte-equal compare (no reduction → exact). */
    double max_delta = 0.0;
    int mismatch_count = 0;
    for (int i = 0; i < N; i++) {
        double d = c_h[i] - c_ref[i];
        if (d != 0.0) {
            mismatch_count++;
            if (d < 0.0) d = -d;
            if (d > max_delta) max_delta = d;
        }
    }
    int numeric_eq_pass = (max_delta == 0.0 && mismatch_count == 0) ? 1 : 0;
    fprintf(stderr, "F-RFC055-NUMERIC-EQ %s — max|Δ| = %.17g, mismatches = %d / %d\n",
            numeric_eq_pass ? "PASS" : "FAIL", max_delta, mismatch_count, N);

    /* Result JSON. */
    FILE* rf = fopen("result.json", "w");
    fprintf(rf, "{\n");
    fprintf(rf, "  \"rfc\": \"055-P1\",\n");
    fprintf(rf, "  \"kernel\": \"vadd\",\n");
    fprintf(rf, "  \"n\": %d,\n", N);
    fprintf(rf, "  \"block_x\": %d,\n", BLOCK);
    fprintf(rf, "  \"grid_x\": %d,\n", grid_x);
    fprintf(rf, "  \"falsifiers\": {\n");
    fprintf(rf, "    \"F-RFC055-PTX-EMIT\":   \"PASS\",\n");
    fprintf(rf, "    \"F-RFC055-LAUNCH-ABI\": \"PASS\",\n");
    fprintf(rf, "    \"F-RFC055-NUMERIC-EQ\": \"%s\",\n", numeric_eq_pass ? "PASS" : "FAIL");
    fprintf(rf, "    \"F-RFC055-NUMERIC-EQ.max_delta\": %.17g,\n", max_delta);
    fprintf(rf, "    \"F-RFC055-NUMERIC-EQ.mismatches\": %d\n", mismatch_count);
    fprintf(rf, "  }\n");
    fprintf(rf, "}\n");
    fclose(rf);
    cuModuleUnload(mod);
    cuCtxDestroy(ctx);
    return numeric_eq_pass ? 0 : 6;
}
HARNESS_C

echo "[0b] host harness materialised ($(wc -l < $HARNESS_C) lines)"

# ── 1) Create runpod pod ──────────────────────────────────────────────
echo "[1/8] Creating runpod pod (gpu=${GPU_ID}, image=${IMAGE})..."
CREATE=$($RUNPODCTL pod create \
    --gpu-id "$GPU_ID" --image "$IMAGE" --container-disk-in-gb 40 \
    --volume-in-gb 0 --ssh --ports "22/tcp" --name "$LABEL" 2>&1)
IID=$(echo "$CREATE"|python3 -c "
import json,sys
try: d=json.load(sys.stdin); print(d.get('id',''))
except: sys.stderr.write(sys.stdin.read()[:300]); sys.exit(1)")
[ -z "$IID" ] && { echo "ERROR: pod create failed: $CREATE"; exit 1; }
echo "  pod: $IID"; echo "$IID" > "$LOCAL_DIR/pod_id.txt"

cleanup(){ local rc=$?
  if [ "${SAVE_POD:-0}" = "1" ]; then echo "[cleanup] SAVE_POD=1 keep $IID"
  else echo "[cleanup] delete $IID"; $RUNPODCTL pod delete "$IID" 2>&1|head -2||true; fi; }
trap cleanup EXIT INT TERM

# ── 2/3) Wait SSH ────────────────────────────────────────────────────
echo "[2-3/8] Waiting runpod SSH ..."
SSH_HOST=""; SSH_PORT=""
for i in $(seq 1 160); do
    INFO=$($RUNPODCTL pod get "$IID" 2>/dev/null||echo "{}")
    ST=$(echo "$INFO"|python3 -c "
import json,sys
try: d=json.load(sys.stdin); print(d.get('desiredStatus','') or d.get('status',''))
except: print('')" 2>/dev/null||echo "")
    if [ "$ST" = "RUNNING" ] || [ "$ST" = "running" ]; then
        SI=$($RUNPODCTL ssh info "$IID" 2>/dev/null||echo "")
        SSH_HOST=$(echo "$SI"|grep -oE '@[^ ]+'|head -1|sed 's/^@//')
        SSH_PORT=$(echo "$SI"|grep -oE -- '-p [0-9]+'|head -1|awk '{print $2}')
        if [ -n "$SSH_HOST" ] && [ -n "$SSH_PORT" ]; then
            if ssh -i "$RUNPOD_SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                -o ConnectTimeout=10 -p "$SSH_PORT" "root@$SSH_HOST" 'echo READY' 2>&1|grep -q READY; then
                echo "  SSH ready: $SSH_HOST:$SSH_PORT"; break
            fi
            SSH_HOST=""
        fi
    fi
    echo "  ... $i/160 status=$ST"; sleep 5
done
[ -z "$SSH_HOST" ] && { echo "ERROR: SSH not ready"; SAVE_POD=1; exit 1; }
SSH_OPTS="-i $RUNPOD_SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=60"
SC="ssh $SSH_OPTS -p $SSH_PORT root@$SSH_HOST"
SCP="scp $SSH_OPTS -P $SSH_PORT -o ConnectTimeout=3600"

# ── 4) Toolchain sanity ───────────────────────────────────────────────
echo "[4/8] Toolchain sanity ..."
$SC "nvidia-smi --query-gpu=name,compute_cap --format=csv,noheader|head -1
nvcc --version|tail -2
which clang||(apt update >/dev/null 2>&1 && apt install -y clang >/dev/null 2>&1 && which clang)
mkdir -p $REMOTE_WORK
echo OK"

# ── 5) upload PTX text + host harness ────────────────────────────────
echo "[5/8] Upload PTX + harness ..."
$SCP "$PTX_OUT"     "root@$SSH_HOST:$REMOTE_WORK/vec_add.ptx"
$SCP "$HARNESS_C"   "root@$SSH_HOST:$REMOTE_WORK/host_vec_add.c"

# ── 6) ptxas → cubin → build harness → fire ──────────────────────────
#
# F-RFC055-PTX-EMIT lives here — ptxas's exit code on the hexa-emitted
# PTX. F-RFC055-NO-LLVM is structural: the `nvcc -dlink` we do NOT
# invoke means there is no LLVM-side link step.
echo "[6/8] ptxas + build + fire ..."
$SC "cd $REMOTE_WORK && \
  GPU_ARCH=\$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader|head -1|tr -d '.\n') ; \
  echo \"GPU_ARCH=sm_\$GPU_ARCH\" ; \
  ptxas -arch=sm_\$GPU_ARCH vec_add.ptx -o vec_add.cubin 2>&1 | tee build.log ; \
  PTXAS_RC=\${PIPESTATUS[0]} ; echo \"PTXAS_RC=\$PTXAS_RC\" ; \
  if [ \"\$PTXAS_RC\" = '0' ]; then \
    echo F-RFC055-PTX-EMIT PASS ; \
    nvcc -O2 -o host_vec_add host_vec_add.c -lcuda 2>&1 | tee -a build.log ; \
    HOST_RC=\${PIPESTATUS[0]} ; echo \"HOST_RC=\$HOST_RC\" ; \
    if [ \"\$HOST_RC\" = '0' ]; then \
      ./host_vec_add vec_add.cubin 2>&1 | tee fire.log ; \
      echo \"FIRE_RC=\${PIPESTATUS[0]}\" ; \
    else echo 'HOST BUILD FAILED'; fi ; \
  else echo 'PTXAS FAILED — F-RFC055-PTX-EMIT FAIL'; fi ; \
  test -f result.json && echo RESULT_JSON_OK || echo RESULT_JSON_MISSING" 2>&1 | tee "$DISPATCH_LOG"

# ── 7) pull artifacts ────────────────────────────────────────────────
echo "[7/8] Pull artifacts ..."
PULL_OK=1
pull(){ local t=0; while [ $t -lt 3 ]; do
  $SCP "root@$SSH_HOST:$REMOTE_WORK/$1" "$LOCAL_DIR/$1" 2>&1 && { echo "  pulled $1"; return 0; }
  t=$((t+1)); echo "  retry $t/3 $1"; [ $t -lt 3 ] && sleep 10; done; echo "  FAIL $1"; return 1; }
$SC "test -f $REMOTE_WORK/result.json && echo OK" 2>/dev/null | grep -q OK \
  && pull result.json || PULL_OK=0
pull build.log || true
pull fire.log || true
pull vec_add.cubin || true   # for offline audit of cubin shape

# ── 8) lifecycle + summary ───────────────────────────────────────────
if [ $PULL_OK -eq 1 ]; then
  echo "[8/8] artifacts pulled — destroy $IID"
  $RUNPODCTL pod delete "$IID" 2>&1|head -2||true; SAVE_POD=0
else
  echo "[8/8] partial pull — pod RETAINED ($IID)"; SAVE_POD=1
fi
echo "=== RFC 055 055-P1 vec-add fire DONE — $(date -u) ==="
[ -f "$LOCAL_DIR/result.json" ] && cat "$LOCAL_DIR/result.json"

# F-RFC055-NO-LLVM — final build-graph audit. The host-side compile
# uses `nvcc + -lcuda` (CUDA Driver API). There is no LLVM linkage in
# the build chain; the local hexa→PTX step is pure-hexa.
if grep -i 'llvm' "$LOCAL_DIR/build.log" 2>/dev/null >/dev/null; then
    echo "F-RFC055-NO-LLVM FAIL — `llvm` appears in build.log"
else
    echo "F-RFC055-NO-LLVM PASS — no LLVM linkage on hexa→PTX path"
fi
echo "DONE"
