// gpu_multiarch_fatbin_host.c
//
// Minimal CUDA Driver-API host that loads an embedded NVIDIA fat binary
// (sm_80 + sm_90 cubins + compute_80 PTX fallback) via cuModuleLoadData,
// launches the INBOX-1665 unop wrapper kernel on whatever real GPU the
// process happens to attach to, and checks the numeric result.
//
// "Multi-arch fat binary" deployment wedge (GPU.md §5 niche). The
// driver auto-selects the closest-fit cubin from the fat blob -- on a
// sm_120 RTX 5070 (no exact match in the fat) it driver-JITs the PTX
// fallback (compute_80) forward into a sm_120 SASS image. Single
// binary, multi-arch GPU coverage, NO libcublas.so dependency.
//
// Reference / NOT-linked: libcublas.so.12 path + size printed by the
// probe shell wrapper for deployment-surface comparison.
//
// Build (see tool/gpu_multiarch_fatbin_probe.hexa):
//   cc -O2 -I$CUDA_HOME/include -I<out_dir>           \
//      -o multiarch_host gpu_multiarch_fatbin_host.c   \
//      -L$CUDA_HOME/lib64 -lcuda
//
// The header foo_fatbin.h is generated by `xxd -i foo.fatbin` inside
// the probe driver and contains:
//   unsigned char foo_fatbin[] = { 0xXX, 0xXX, ... };
//   unsigned int  foo_fatbin_len = NNNN;
//
// PASS marker: printf("RESULT: PASS ...") on numerically exact f64 eq.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cuda.h>

// Generated by xxd -i; the probe driver puts it next to this .c.
#include "foo_fatbin.h"

#define CHK(call) do { \
    CUresult r = (call); \
    if (r != CUDA_SUCCESS) { \
        const char *m; cuGetErrorString(r, &m); \
        fprintf(stderr, "CUDA err %d: %s at %s:%d\n", r, m, __FILE__, __LINE__); \
        return 1; \
    } \
} while (0)

int main(void) {
    CHK(cuInit(0));
    CUdevice dev;
    CHK(cuDeviceGet(&dev, 0));

    char name[256];
    int sm_major = 0, sm_minor = 0;
    CHK(cuDeviceGetName(name, sizeof(name), dev));
    CHK(cuDeviceGetAttribute(&sm_major,
        CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, dev));
    CHK(cuDeviceGetAttribute(&sm_minor,
        CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, dev));
    printf("multi-arch fatbin host loader\n");
    printf("  device     : %s\n", name);
    printf("  capability : sm_%d%d\n", sm_major, sm_minor);
    printf("  fatbin size: %u bytes (embedded in host binary)\n",
           foo_fatbin_len);

    CUcontext ctx;
    CHK(cuCtxCreate(&ctx, 0, dev));

    // cuModuleLoadData accepts a fat binary blob directly; the driver
    // walks the fat index, finds the best match for the current arch
    // (exact cubin if present; else JIT the PTX fallback), and loads.
    CUmodule mod;
    char err_log[8192]; err_log[0] = 0;
    CUjit_option opts[3] = {
        CU_JIT_ERROR_LOG_BUFFER,
        CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES,
        CU_JIT_LOG_VERBOSE
    };
    unsigned int log_sz = sizeof(err_log);
    void *vals[3] = { err_log, (void*)(uintptr_t)log_sz, (void*)(uintptr_t)1 };

    CUresult r = cuModuleLoadDataEx(&mod, foo_fatbin, 3, opts, vals);
    if (r != CUDA_SUCCESS) {
        const char *m; cuGetErrorString(r, &m);
        fprintf(stderr, "cuModuleLoadDataEx (fatbin) err %d: %s\n", r, m);
        fprintf(stderr, "JIT err log:\n%s\n", err_log);
        return 1;
    }
    printf("  load       : OK (driver picked image for sm_%d%d)\n",
           sm_major, sm_minor);

    CUfunction kfn;
    CHK(cuModuleGetFunction(&kfn, mod, "unop_neg_kernel"));

    CUdeviceptr d_in, d_out;
    CHK(cuMemAlloc(&d_in,  sizeof(double)));
    CHK(cuMemAlloc(&d_out, sizeof(double)));
    double x = -2.0;
    double y = 99.0;
    CHK(cuMemcpyHtoD(d_in, &x, sizeof(double)));
    CHK(cuMemcpyHtoD(d_out, &y, sizeof(double)));

    void *args[] = { &d_out, &d_in };
    CHK(cuLaunchKernel(kfn, 1,1,1, 1,1,1, 0, NULL, args, NULL));
    CHK(cuCtxSynchronize());

    double got;
    CHK(cuMemcpyDtoH(&got, d_out, sizeof(double)));

    double want = -5.25;
    printf("  kernel     : x=%.3f -> y=%.6f (want=%.6f)\n", x, got, want);
    if (got == want) {
        printf("  RESULT: PASS (exact f64 equality, multi-arch fatbin loaded)\n");
        cuMemFree(d_in); cuMemFree(d_out);
        cuModuleUnload(mod);
        cuCtxDestroy(ctx);
        return 0;
    }
    printf("  RESULT: FAIL got=%.17g want=%.17g\n", got, want);
    return 1;
}
