#!/usr/bin/env bash
# tool/regen_runtime_core_c.sh — deterministic, hexat-FREE regen of the generated
# artifact self/runtime_core.c from its emitter SSOT self/runtime_core_emit.hexa.
#
# WHY THIS EXISTS (zero-c leg-B r2a, alloc multiple-definition wall):
#   self/runtime_core.c is a GENERATED, .gitignore'd artifact. On a CLEAN
#   checkout STAGE-0 (tool/stage_resolve_runtime_a) regenerates it from the
#   emitter, so it is always guard-consistent. But on a WARM tree (a re-run, or
#   the CI `-v <hexat>` path that supplies an existing transpiler) build_aprime.sh
#   STAGE-0 SKIPS regen — and if a STALE self/runtime_core.c is sitting in the
#   tree (generated by a pre-#3583 emitter that emitted the C arena body
#   UNCONDITIONALLY, before the `#ifdef HEXA_RT_ALLOC_NATIVE / #else` guard), then
#   compiling it with -DHEXA_RT_ALLOC_NATIVE=1 leaves the C `hexa_arena_alloc`
#   body in the TU WHILE the native seed alloc_syscall_native.o ALSO defines
#   `hexa_arena_alloc` → `multiple definition of hexa_arena_alloc` link fail.
#   The alloc seed is uniquely name-colliding (the array/map/str seeds use a
#   DISTINCT `rt_*_native` symbol the C body merely delegates to, so a stale
#   sibling .c never clashes); only alloc shares the public symbol name, which is
#   why only alloc needs the C body to #else-drop, and why only alloc is fragile
#   to a stale warm-tree artifact.
#
# THE FIX: regenerate runtime_core.c from the emitter SSOT on the warm path too,
# so the guard is always present + consistent regardless of HEXA_RT_ALLOC_NATIVE.
# The regen is byte-DETERMINISTIC (the awk un-escape reproduces the emitter's own
# .c output verbatim), so an ALREADY-FRESH tree gets a SHA-identical file — this
# is byte-neutral (no perf change, no byteeq drift). A STALE tree gets corrected.
#
# This is the SAME un-escaper stage_resolve_runtime_a uses for its PRIMARY regen
# path (factored here so build_aprime.sh's warm path reuses it verbatim — DRY,
# reference-first: copy the working sibling, do not reinvent).
#
# Usage:  bash tool/regen_runtime_core_c.sh [REPO_ROOT]
#   REPO_ROOT defaults to $PWD; must contain self/runtime_core_emit.hexa.
# Idempotent + NO-OP-SAFE: emitter absent → keep in-tree .c (return 0, no change).
set -u

ROOT="${1:-$PWD}"
EMITTER="$ROOT/self/runtime_core_emit.hexa"
DST="$ROOT/self/runtime_core.c"

# Deterministic, hexat-FREE un-escaper for a *_emit.hexa SSOT → its emitted .c.
# The emitter bodies are pure `    buf = buf + "<C-line>"` literals whose
# un-escaped (\n \t \" \\) content IS the .c text VERBATIM. Returns 3 if the
# emitter has no recognizable buf-literal lines.
_unescape_emit_to_c() {
    awk '
      BEGIN { saw = 0 }
      {
        line = $0
        pfx = "    buf = buf + \""
        if (substr(line, 1, length(pfx)) != pfx) next
        body = substr(line, length(pfx) + 1)
        if (substr(body, length(body), 1) != "\"") next
        body = substr(body, 1, length(body) - 1)
        saw = 1
        out = ""; n = length(body); i = 1
        while (i <= n) {
          c = substr(body, i, 1)
          if (c == "\\" && i < n) {
            d = substr(body, i+1, 1)
            if (d == "n")  { out = out "\n"; i += 2; continue }
            if (d == "t")  { out = out "\t"; i += 2; continue }
            if (d == "\"") { out = out "\""; i += 2; continue }
            if (d == "\\") { out = out "\\"; i += 2; continue }
            out = out "\\"; i += 1; continue
          }
          out = out c; i += 1
        }
        printf "%s", out
      }
      END { if (!saw) exit 3 }
    ' "$1"
}

[ -f "$EMITTER" ] || { echo "[regen_runtime_core_c] SKIP — emitter absent ($EMITTER)"; exit 0; }

atmp="$(mktemp -t regen_runtime_core_c.XXXXXX)" || atmp=""
if [ -n "$atmp" ] && _unescape_emit_to_c "$EMITTER" > "$atmp" 2>/dev/null \
   && [ -s "$atmp" ] && grep -q 'HexaVal hexa_str_join' "$atmp"; then
    # Only overwrite (and announce) when the content actually differs, so a fresh
    # warm tree is a true no-op and the message noise stays meaningful.
    if [ ! -f "$DST" ] || ! cmp -s "$atmp" "$DST"; then
        cp -f "$atmp" "$DST"
        echo "[regen_runtime_core_c] runtime_core.c SYNTHESIZED from emitter SSOT (awk un-escape, $(wc -l < "$DST") lines, hexat-free) — was stale/absent"
    else
        echo "[regen_runtime_core_c] runtime_core.c already fresh (byte-identical to emitter SSOT) — no-op"
    fi
    rm -f "$atmp"
    exit 0
fi
rm -f "$atmp"
echo "[regen_runtime_core_c] SKIP — emitter has no recognizable buf-literal lines (in-tree .c kept)" >&2
exit 0
