#!/usr/bin/env bash
# tool/regen_rtcore_arith-coerce-format_c.sh — deterministic, hexat-FREE regen
# of the generated seed artifact self/native/rtcore_arith-coerce-format.c from
# its emitter SSOT self/native/rtcore_arith-coerce-format_emit.hexa (zero-c
# leg-B recursive campaign, ING #29).
#
# WHY THIS EXISTS:
#   self/native/rtcore_arith-coerce-format.c is now a GENERATED, .gitignore'd
#   artifact. The emitter rtcore_arith-coerce-format_emit.hexa is the tracked
#   SSOT (generated by tool/gen_c_text_emitter.hexa from the hand-assembled .c,
#   byte-identical BY CONSTRUCTION). The native-.o regen
#   (tool/regen_rtcore_arith-coerce-format_native_o.sh) calls THIS first so the
#   .c is always present + fresh before it is compiled into the seed .o.
#
# This is the SAME awk un-escaper tool/regen_runtime_core_c.sh /
# regen_runtime_hi_seed_c.sh use (the emitter bodies are pure
# `    buf = buf + "<C-line>"` literals whose un-escaped \n \t \" \\ content IS
# the .c text VERBATIM). The regen is byte-DETERMINISTIC: an already-fresh tree
# gets a SHA-identical file (byte-neutral; no perf change, no byteeq drift).
#
# Usage:  bash tool/regen_rtcore_arith-coerce-format_c.sh [REPO_ROOT]
#   REPO_ROOT defaults to $PWD; must contain
#   self/native/rtcore_arith-coerce-format_emit.hexa.
# Idempotent + NO-OP-SAFE: emitter absent → keep in-tree .c (return 0, no change).
set -u

ROOT="${1:-$PWD}"
EMITTER="$ROOT/self/native/rtcore_arith-coerce-format_emit.hexa"
DST="$ROOT/self/native/rtcore_arith-coerce-format.c"

_unescape_emit_to_c() {
    awk '
      BEGIN { saw = 0 }
      {
        line = $0
        pfx = "    buf = buf + \""
        if (substr(line, 1, length(pfx)) != pfx) next
        body = substr(line, length(pfx) + 1)
        if (substr(body, length(body), 1) != "\"") next
        body = substr(body, 1, length(body) - 1)
        saw = 1
        out = ""; n = length(body); i = 1
        while (i <= n) {
          c = substr(body, i, 1)
          if (c == "\\" && i < n) {
            d = substr(body, i+1, 1)
            if (d == "n")  { out = out "\n"; i += 2; continue }
            if (d == "t")  { out = out "\t"; i += 2; continue }
            if (d == "\"") { out = out "\""; i += 2; continue }
            if (d == "\\") { out = out "\\"; i += 2; continue }
            out = out "\\"; i += 1; continue
          }
          out = out c; i += 1
        }
        printf "%s", out
      }
      END { if (!saw) exit 3 }
    ' "$1"
}

[ -f "$EMITTER" ] || { echo "[regen_rtcore_arith-coerce-format_c] SKIP — emitter absent ($EMITTER)"; exit 0; }
mkdir -p "$(dirname "$DST")"

atmp="$(mktemp -t regen_rtcore_acf_c.XXXXXX)" || atmp=""
if [ -n "$atmp" ] && _unescape_emit_to_c "$EMITTER" > "$atmp" 2>/dev/null \
   && [ -s "$atmp" ] && grep -q "HexaVal hexa_str_char_at(HexaVal s, HexaVal idx)" "$atmp"; then
    if [ ! -f "$DST" ] || ! cmp -s "$atmp" "$DST"; then
        cp -f "$atmp" "$DST"
        echo "[regen_rtcore_arith-coerce-format_c] rtcore_arith-coerce-format.c SYNTHESIZED from emitter SSOT ($(wc -l < "$DST") lines, hexat-free) — was stale/absent"
    else
        echo "[regen_rtcore_arith-coerce-format_c] rtcore_arith-coerce-format.c already fresh (byte-identical) — no-op"
    fi
    rm -f "$atmp"
    exit 0
fi
rm -f "$atmp"
echo "[regen_rtcore_arith-coerce-format_c] SKIP — emitter has no recognizable buf-literal lines (in-tree .c kept)" >&2
exit 0
