#!/usr/bin/env bash
# tool/regen_rtcore_collection-mutate_c.sh — deterministic, hexat-FREE regen of
# the generated artifact self/native/rtcore_collection-mutate.c from its emitter
# SSOT self/native/rtcore_collection-mutate_emit.hexa.
#
# WHY THIS EXISTS (zero-c leg-B, ING #29 — fewer tracked self/**/*.c):
#   self/native/rtcore_collection-mutate.c is a zero-c leg-B native seed (13
#   map/array mutate+query symbols externed out of runtime_core.c under
#   -DHEXA_RT_CORE_COLLECTION_MUTATE_NATIVE, compiled to a SEPARATE .o by
#   tool/regen_rtcore_collection-mutate_native_o.sh). It used to be hand-tracked
#   in git. This script makes the .hexa emitter the SSOT and the .c a
#   regenerated/.gitignore'd build artifact (exactly like the runtime_core trio:
#   self/runtime_core.c <- self/runtime_core_emit.hexa via regen_runtime_core_c.sh).
#
#   The emitter was generated by tool/gen_c_text_emitter.hexa, which emits each
#   source line as `    buf = buf + "<escaped-line>\n"`. The awk un-escaper below
#   is the SAME one regen_runtime_core_c.sh uses (it reproduces the .c VERBATIM).
#
# TRAILING-NEWLINE NOTE (byte-identity, root-cause):
#   The committed seed has NO final newline (last byte is `}`). The generator
#   appends `\n` to EVERY line, so the raw un-escape would carry one extra
#   trailing newline. To keep the regenerated .c BYTE-IDENTICAL to the committed
#   seed (cmp exit 0 -> byte-neutral build, no .o drift, no byteeq drift), this
#   script strips exactly one trailing newline from the un-escaped output. The
#   first 13712 bytes are reproduced verbatim; only the synthetic final newline
#   is removed. (If the source ever gains a real final newline, the emitter would
#   carry a blank last line and the strip would still produce the source verbatim.)
#
# This regen is byte-DETERMINISTIC: an ALREADY-FRESH tree gets a SHA-identical
# file (byte-neutral, no perf/byteeq change); a STALE/absent tree gets corrected.
#
# Usage:  bash tool/regen_rtcore_collection-mutate_c.sh [REPO_ROOT]
#   REPO_ROOT defaults to $PWD; must contain
#   self/native/rtcore_collection-mutate_emit.hexa.
# Idempotent + NO-OP-SAFE: emitter absent -> keep in-tree .c (return 0, no change).
set -u

ROOT="${1:-$PWD}"
EMITTER="$ROOT/self/native/rtcore_collection-mutate_emit.hexa"
DST="$ROOT/self/native/rtcore_collection-mutate.c"

# Deterministic, hexat-FREE un-escaper for a *_emit.hexa SSOT -> its emitted .c.
# The emitter bodies are pure `    buf = buf + "<C-line>"` literals whose
# un-escaped (\n \t \" \\) content IS the .c text VERBATIM. Returns 3 if the
# emitter has no recognizable buf-literal lines.
_unescape_emit_to_c() {
    awk '
      BEGIN { saw = 0 }
      {
        line = $0
        pfx = "    buf = buf + \""
        if (substr(line, 1, length(pfx)) != pfx) next
        body = substr(line, length(pfx) + 1)
        if (substr(body, length(body), 1) != "\"") next
        body = substr(body, 1, length(body) - 1)
        saw = 1
        out = ""; n = length(body); i = 1
        while (i <= n) {
          c = substr(body, i, 1)
          if (c == "\\" && i < n) {
            d = substr(body, i+1, 1)
            if (d == "n")  { out = out "\n"; i += 2; continue }
            if (d == "t")  { out = out "\t"; i += 2; continue }
            if (d == "\"") { out = out "\""; i += 2; continue }
            if (d == "\\") { out = out "\\"; i += 2; continue }
            out = out "\\"; i += 1; continue
          }
          out = out c; i += 1
        }
        printf "%s", out
      }
      END { if (!saw) exit 3 }
    ' "$1"
}

[ -f "$EMITTER" ] || { echo "[regen_rtcore_collection-mutate] SKIP — emitter absent ($EMITTER)"; exit 0; }

atmp="$(mktemp -t regen_rtcore_collection-mutate.XXXXXX)" || atmp=""
if [ -n "$atmp" ] && _unescape_emit_to_c "$EMITTER" > "$atmp" 2>/dev/null \
   && [ -s "$atmp" ] && grep -q 'hexa_map_remove_impl' "$atmp"; then
    # The committed seed has NO final newline; the generator appends one to every
    # line. Strip exactly one trailing newline so the regen is byte-identical to
    # the committed .c (printf '%s' re-emits the body WITHOUT adding a newline).
    btmp="$(mktemp -t regen_rtcore_collection-mutate2.XXXXXX)" || btmp=""
    if [ -n "$btmp" ]; then
        printf '%s' "$(cat "$atmp")" > "$btmp"
        mv -f "$btmp" "$atmp"
    fi
    # Only overwrite (and announce) when content actually differs, so a fresh
    # warm tree is a true no-op and the message noise stays meaningful.
    if [ ! -f "$DST" ] || ! cmp -s "$atmp" "$DST"; then
        cp -f "$atmp" "$DST"
        echo "[regen_rtcore_collection-mutate] rtcore_collection-mutate.c SYNTHESIZED from emitter SSOT (awk un-escape, $(wc -l < "$DST") lines, hexat-free) — was stale/absent"
    else
        echo "[regen_rtcore_collection-mutate] rtcore_collection-mutate.c already fresh (byte-identical to emitter SSOT) — no-op"
    fi
    rm -f "$atmp"
    exit 0
fi
rm -f "$atmp"
echo "[regen_rtcore_collection-mutate] SKIP — emitter has no recognizable buf-literal lines (in-tree .c kept)" >&2
exit 0
