## tool/regen_cc_merge.awk — hexa_cc.c regen pass 1: rename per-module main()
##
## Ported from self/main.hexa::merge_modules_awk (Phase C MVP heredoc) so the
## awk lives on-disk as a tracked file instead of an embedded hexa string.
## Required for the RFC 086 P0 bypass — the in-process hexa-runtime `exec()`
## chain (cmd_regen_cc) silent-truncates /tmp/_cg.c to a 259 B skeleton;
## driving each module via direct shell instead reaches the full 940 KB
## transpile output reliably. See docs/rfc/rfc_drafts/rfc_086* (removed in
## this same PR — RFC closed by implementation).
##
## Invoke: awk -v MOD=lexer  -f regen_cc_merge.awk <in.c>  > <out.c>
##         awk -v MOD=parser -f regen_cc_merge.awk ...
##
## Behavior:
##   - drop `#include` lines (single dedup'd #include emitted in header)
##   - drop the auto-generated `// Generated by HEXA self-host compiler` line
##   - rename each module's `int main(int argc, char** argv) {` to
##     `int _<MOD>_init(int argc, char** argv) {`, leaving the body intact
##     so module-level init code (globals like p_max_errors, _known_fn_globals,
##     etc.) still runs when the merged dispatcher calls each init explicitly.
##   - column-0 `}` terminates the renamed block (depth-tracking variant was
##     broken by `}` chars in string literals).

BEGIN { in_main = 0 }
/^#include/ { next }
/^\/\/ Generated by/ { next }
/^int main\(/ {
    printf("int _%s_init(int argc, char** argv) {\n", MOD)
    in_main = 1
    next
}
in_main == 1 && /^\}$/ { print "}"; in_main = 0; next }
in_main == 1 { print; next }
{ print }
