#!/usr/bin/env bash
# tool/regen_rtcore_runtime-misc_c.sh — deterministic, hexat-FREE regen of the generated
# artifact self/native/rtcore_runtime-misc.c from its emitter SSOT
# self/native/rtcore_runtime-misc_emit.hexa (zero-c leg-B, ING #29).
#
# WHY THIS EXISTS:
#   self/native/rtcore_runtime-misc.c was a hand-assembled, git-TRACKED zero-c leg-B
#   native seed. It is now a GENERATED, .gitignore'd artifact whose SSOT is the
#   hexa text-emitter self/native/rtcore_runtime-misc_emit.hexa (built by
#   tool/gen_c_text_emitter.hexa). This brings rtcore_runtime-misc into the same
#   emitter-SSOT discipline as the rest of the rtcore family — one fewer tracked
#   self/**/*.c. (11 runtime-misc symbols (__vs_ptr_eq/.../__hexa_try_cleanup).)
#
#   This .c is NO-FINAL-NEWLINE-terminated (last byte 0x7d '}'); the emitter that
#   produced it was generated by the gen_c_text_emitter no-final-newline root-cause
#   fix, so the awk un-escape below reproduces the .c (incl. its missing trailing
#   newline) byte-identically.
#
#   regen_rtcore_runtime-misc_native_o.sh #include's self/native/rtcore_runtime-misc.c to build
#   the seed .o, so the .c must be present before that compile. This script
#   regenerates it byte-identically from the emitter; the awk un-escape
#   reproduces the emitter's own .c output VERBATIM (proven cmp exit 0), so an
#   already-fresh tree gets a SHA-identical file — byte-neutral (no perf change,
#   no byteeq drift).
#
# This is the SAME un-escaper tool/regen_runtime_core_c.sh uses (factored here so
# the seed-.o build reuses it verbatim — DRY, reference-first: copy the working
# sibling, do not reinvent).
#
# Usage:  bash tool/regen_rtcore_runtime-misc_c.sh [REPO_ROOT]
#   REPO_ROOT defaults to $PWD; must contain self/native/rtcore_runtime-misc_emit.hexa.
# Idempotent + NO-OP-SAFE: emitter absent -> keep in-tree .c (return 0, no change).
set -u

ROOT="${1:-$PWD}"
EMITTER="$ROOT/self/native/rtcore_runtime-misc_emit.hexa"
DST="$ROOT/self/native/rtcore_runtime-misc.c"

# Deterministic, hexat-FREE un-escaper for a *_emit.hexa SSOT -> its emitted .c.
# The emitter bodies are pure `    buf = buf + "<C-line>"` literals whose
# un-escaped (\n \t \" \\) content IS the .c text VERBATIM. Returns 3 if the
# emitter has no recognizable buf-literal lines.
_unescape_emit_to_c() {
    awk '
      BEGIN { saw = 0 }
      {
        line = $0
        pfx = "    buf = buf + \""
        if (substr(line, 1, length(pfx)) != pfx) next
        body = substr(line, length(pfx) + 1)
        if (substr(body, length(body), 1) != "\"") next
        body = substr(body, 1, length(body) - 1)
        saw = 1
        out = ""; n = length(body); i = 1
        while (i <= n) {
          c = substr(body, i, 1)
          if (c == "\\" && i < n) {
            d = substr(body, i+1, 1)
            if (d == "n")  { out = out "\n"; i += 2; continue }
            if (d == "t")  { out = out "\t"; i += 2; continue }
            if (d == "\"") { out = out "\""; i += 2; continue }
            if (d == "\\") { out = out "\\"; i += 2; continue }
            out = out "\\"; i += 1; continue
          }
          out = out c; i += 1
        }
        printf "%s", out
      }
      END { if (!saw) exit 3 }
    ' "$1"
}

[ -f "$EMITTER" ] || { echo "[regen_rtcore_runtime-misc_c] SKIP — emitter absent ($EMITTER)"; exit 0; }

atmp="$(mktemp -t regen_rtcore_runtime-misc_c.XXXXXX)" || atmp=""
if [ -n "$atmp" ] && _unescape_emit_to_c "$EMITTER" > "$atmp" 2>/dev/null \
   && [ -s "$atmp" ] && grep -qF 'HexaVal hexa_index_get(HexaVal container, HexaVal key) {' "$atmp"; then
    # Only overwrite (and announce) when the content actually differs, so a fresh
    # warm tree is a true no-op and the message noise stays meaningful.
    if [ ! -f "$DST" ] || ! cmp -s "$atmp" "$DST"; then
        cp -f "$atmp" "$DST"
        echo "[regen_rtcore_runtime-misc_c] rtcore_runtime-misc.c SYNTHESIZED from emitter SSOT (awk un-escape, $(wc -l < "$DST") lines, hexat-free) — was stale/absent"
    else
        echo "[regen_rtcore_runtime-misc_c] rtcore_runtime-misc.c already fresh (byte-identical to emitter SSOT) — no-op"
    fi
    rm -f "$atmp"
    exit 0
fi
rm -f "$atmp"
echo "[regen_rtcore_runtime-misc_c] SKIP — emitter has no recognizable buf-literal lines (in-tree .c kept)" >&2
exit 0
