#!/usr/bin/env python3
# design.py - `chip + design` producer (D72 adapter-only · firmware-stub
# pattern · D111 cellrun-compatible · yosys synth-script template).
#
# Emits chip_v1.meta.json + chip_design_v1.yosys_script.ys +
# chip_design_v1.dossier.md + chip_design_<stamp>.json (4 artifacts ·
# sscb design.py mirror).
#
# Reads the `--rtl <path>` Verilog file and produces:
#   - A yosys synthesis script template (`read_verilog · hierarchy ·
#     synth -top · dfflibmap -liberty <sky130> · abc -liberty <sky130> ·
#     opt_clean · stat`) — script ready to feed to yosys -s.
#   - A design dossier with constraints (target_freq · area_budget ·
#     timing margin · cell library) and a brief Verilog summary.
#
# This producer DOES NOT spawn yosys (analyze + synthesize cells are
# the yosys consumers). It emits the script so downstream cells can
# `yosys -s chip_design_v1.yosys_script.ys` directly.
#
# argv:
#   chip/design.py <output_dir> [--rtl <path>]
#
# g3: honest. Datasheet/.lib binding = SKY130 placeholder path (vendor
#     PDK location varies per host); script is a template, NOT a tuned
#     PPA-optimized synth flow. absorbed=false permanently.

from __future__ import annotations

import json
import platform
import sys
import time
from pathlib import Path
from typing import Optional

GEOMETRY_ID = "chip_design_v1"
META_ID = "chip_v1"

DEFAULT_RTL = "/Users/ghost/core/demiurge/archive/comb/rtl/counter4.v"

# Default SKY130 .lib path — host-dependent. analyze + synthesize cells
# resolve this at run-time; here we record it as a string so the script
# is self-contained.
SKY130_LIB_CANDIDATES = [
    "/Users/ghost/.pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib",
    "/opt/skywater-pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib",
    "$PDK_ROOT/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib",
]


def _parse_argv(argv: list[str]) -> tuple[str, Optional[str]]:
    out_dir = "/tmp/chip_design"
    rtl_path: Optional[str] = None
    i = 1
    positional: list[str] = []
    while i < len(argv):
        tok = argv[i]
        if tok == "--rtl" and i + 1 < len(argv):
            rtl_path = argv[i + 1]
            i += 2
            continue
        positional.append(tok)
        i += 1
    if positional:
        out_dir = positional[0]
    return out_dir, rtl_path


def _resolve_sky130_lib() -> tuple[Optional[str], bool]:
    """Return (lib_path, found) — first candidate that exists, else last
    candidate (env-var template) and found=False (honest gap)."""
    for cand in SKY130_LIB_CANDIDATES:
        if not cand.startswith("$") and Path(cand).is_file():
            return cand, True
    return SKY130_LIB_CANDIDATES[-1], False


def _read_rtl(rtl_path: str) -> tuple[str, int, Optional[str]]:
    """Read the RTL file; return (top_module_guess, loc, error)."""
    p = Path(rtl_path)
    try:
        text = p.read_text(encoding="utf-8")
    except Exception as e:
        return p.stem, 0, str(e)
    loc = text.count("\n") + 1
    # Module-name regex (lightweight · matches structure.py).
    import re
    m = re.search(r"\bmodule\s+([A-Za-z_]\w*)\s*[\(;]", text)
    top = m.group(1) if m else p.stem
    return top, loc, None


def _build_yosys_script(rtl_path: str, top: str, sky130_lib: str) -> str:
    """Compose the yosys synth script template."""
    return f"""# chip_design_v1.yosys_script.ys
# Generated by stdlib/chip/design.py (template emit · sscb design.py mirror).
# Run: yosys -s chip_design_v1.yosys_script.ys
#
# Pipeline: read_verilog → hierarchy → synth → dfflibmap → abc → opt_clean → stat.
# Cell library: SKY130 high-density (sky130_fd_sc_hd · 9-track).
# Synth tool: yosys 0.65 + ABC.

# 1 · frontend (Verilog-2005 synthesizable subset).
read_verilog -sv {rtl_path}

# 2 · hierarchy + flatten + check.
hierarchy -check -top {top}
proc; opt; check

# 3 · synth (generic tech mapping).
synth -top {top}

# 4 · DFF mapping (technology-specific flop bind).
dfflibmap -liberty {sky130_lib}

# 5 · combinational tech mapping via ABC.
abc -liberty {sky130_lib}

# 6 · clean + final stat.
opt_clean -purge
stat -liberty {sky130_lib}

# 7 · write post-synth Verilog (consumed by verify cell's equiv_make).
write_verilog chip_design_v1.synth.v
"""


def main(argv: list[str]) -> int:
    out_dir, rtl_path = _parse_argv(argv)
    rtl = rtl_path or DEFAULT_RTL
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    produced_at_utc = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    top, loc, read_err = _read_rtl(rtl)
    sky130_lib, sky130_found = _resolve_sky130_lib()
    yosys_script = _build_yosys_script(rtl, top, sky130_lib)

    script_path = out / f"{GEOMETRY_ID}.yosys_script.ys"
    script_path.write_text(yosys_script, encoding="utf-8")

    # Constraints — template scaffold (no PPA tuning here).
    constraints = {
        "target_freq_mhz": 100,
        "clock_period_ns": 10.0,
        "timing_margin_pct": 10,
        "area_budget_um2": 10_000,
        "cell_library": "sky130_fd_sc_hd",
        "sky130_lib_path": sky130_lib,
        "sky130_lib_found": sky130_found,
        "synth_tool_chain": [
            "read_verilog -sv",
            "hierarchy -check -top",
            "proc; opt; check",
            "synth -top",
            "dfflibmap -liberty <sky130>",
            "abc -liberty <sky130>",
            "opt_clean -purge",
            "stat -liberty <sky130>",
            "write_verilog <out>.synth.v",
        ],
    }

    dossier_lines = [
        f"# chip design dossier — {top} (design cell template emit)",
        "",
        f"Stamp: {stamp}",
        f"RTL: {rtl}",
        f"Top module: {top}",
        f"LOC: {loc}",
        "",
        "## Constraints",
        "",
        f"- Target frequency: {constraints['target_freq_mhz']} MHz "
        f"(clock period {constraints['clock_period_ns']} ns)",
        f"- Timing margin: {constraints['timing_margin_pct']}%",
        f"- Area budget: {constraints['area_budget_um2']} µm²",
        f"- Cell library: {constraints['cell_library']}",
        "",
        "## SKY130 PDK",
        "",
        f"- Lib path: `{sky130_lib}`",
        f"- Lib found on this host: **{sky130_found}**",
        ("- If False: synthesize cell will graceful-skip with honest-gap "
         "caveat (PDK absence)."),
        "",
        "## Synth tool chain",
        "",
    ]
    dossier_lines.extend(f"- `{step}`" for step in constraints["synth_tool_chain"])
    dossier_lines.extend([
        "",
        "## Yosys script artifact",
        "",
        f"- `{script_path.name}` — runnable via `yosys -s {script_path.name}`.",
        "- Downstream consumers: analyze + synthesize cells (this producer "
        "does NOT spawn yosys).",
        "",
        "## Honest-skip caveats (g3)",
        "",
    ])

    citations = [
        "chip.demi [cell.design] — chip_design_record kind.",
        "Yosys 0.65 manual — yosyshq.net/yosys/documentation.html "
        "(synth · dfflibmap · abc commands).",
        "SKY130 PDK (Google + SkyWater · Apache-2.0) — sky130_fd_sc_hd "
        "high-density 9-track cell library.",
        "ABC (Berkeley · UC Regents) — combinational tech mapping.",
        "stdlib/sscb/design.py — netlist + dossier template mirror.",
    ]
    scope_caveats = [
        "Yosys script is a TEMPLATE emit · NOT a PPA-tuned flow · downstream "
        "synthesize cell may need command tweaks per chip family.",
        "Constraint values (100 MHz · 10K µm²) are clean-room-phase-a "
        "aspirations · NOT tapeout-validated · NOT timing-closed.",
        "SKY130 .lib path is host-dependent · resolved at design-cell "
        "time · synthesize cell re-resolves at run-time.",
        "absorbed=false PERMANENTLY · a synth script template without "
        "post-synth measurement is illustrative, not absorption.",
    ]
    if not sky130_found:
        scope_caveats.append(
            f"SKY130 .lib NOT found at any of {len(SKY130_LIB_CANDIDATES)} "
            "candidate paths — script will fail at dfflibmap step "
            "(synthesize cell graceful-skip).")
    if read_err:
        scope_caveats.append(f"RTL read warning: {read_err}")
    dossier_lines.extend(f"- {c}" for c in scope_caveats)
    dossier_lines.append("")

    dossier_path = out / f"{GEOMETRY_ID}.dossier.md"
    dossier_path.write_text("\n".join(dossier_lines), encoding="utf-8")

    measurements = {
        "target_freq_mhz": constraints["target_freq_mhz"],
        "clock_period_ns": constraints["clock_period_ns"],
        "area_budget_um2": constraints["area_budget_um2"],
        "synth_tool_chain_step_count": len(constraints["synth_tool_chain"]),
        "sky130_lib_found": 1 if sky130_found else 0,
        "loc": loc,
    }

    meta = {
        "ok": True,
        "geometry_id": META_ID,
        "produced_at_utc": produced_at_utc,
        "python_version": platform.python_version(),
        "gate_type": "hexa-native-absent",
        "provisional": True,
        "measurements": measurements,
        "constraints": constraints,
        "rtl_path": rtl,
        "rtl_top": top,
        "artifacts": {
            "yosys_script": script_path.name,
            "dossier": dossier_path.name,
        },
        "provenance": {
            "measurement_gate": "GATE_OPEN",
            "absorbed": False,
            "scope_caveats": scope_caveats,
        },
    }
    meta_path = out / f"{META_ID}.meta.json"
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, sort_keys=True)
        f.write("\n")

    record = {
        "domain": "chip",
        "verb": "design",
        "kind": "chip_design_record",
        "stamp": stamp,
        "producer": "chip_design@template",
        "measurement_gate": "GATE_OPEN",
        "absorbed": False,
        "scope_caveats": scope_caveats,
        "citations": citations,
        "skipped_reason": None,
        "gate_type": "hexa-native-absent",
        "provisional": True,
        "rtl_path": rtl,
        "rtl_top": top,
        "rtl_loc": loc,
        "yosys_script_file": script_path.name,
        "dossier_file": dossier_path.name,
        "target_freq_mhz": constraints["target_freq_mhz"],
        "clock_period_ns": constraints["clock_period_ns"],
        "area_budget_um2": constraints["area_budget_um2"],
        "cell_library": constraints["cell_library"],
        "sky130_lib_path": sky130_lib,
        "sky130_lib_found": sky130_found,
        "synth_tool_chain": constraints["synth_tool_chain"],
        "notes": (
            "Yosys synth script template emit + design constraints "
            "(target_freq · area_budget · SKY130 cell library). "
            "Downstream cells (analyze · synthesize · verify) run yosys."
        ),
        "artifacts": {
            "meta": meta_path.name,
            "yosys_script": script_path.name,
            "dossier": dossier_path.name,
        },
    }
    rec_path = out / f"chip_design_{stamp}.json"
    with open(rec_path, "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2, sort_keys=True)
        f.write("\n")

    sys.stderr.write(
        f"chip_design: wrote {rec_path} "
        f"(ok=True, top='{top}', loc={loc}, "
        f"target_freq_mhz={constraints['target_freq_mhz']}, "
        f"sky130_lib_found={sky130_found})\n")

    summary = {
        "ok": True,
        "geometry_id": META_ID,
        "gate_type": "hexa-native-absent",
        "provisional": True,
        "rtl_top": top,
        "rtl_loc": loc,
        "target_freq_mhz": constraints["target_freq_mhz"],
        "area_budget_um2": constraints["area_budget_um2"],
        "sky130_lib_found": sky130_found,
        "artifacts": {
            "record": rec_path.name,
            "meta": meta_path.name,
            "yosys_script": script_path.name,
            "dossier": dossier_path.name,
        },
    }
    sys.stderr.write("CHIP_DESIGN_RESULT "
                     + json.dumps(summary, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
