#!/usr/bin/env bash
# flame-forge dojo run glue — generated by stdlib/dojo/flame_forge
# slug: mlp  ·  kata: mlp
set -euo pipefail
cd "$(dirname "$0")"

# ── cloud DDP path (DOJO_CLOUD=1) — NO-TROUBLESHOOT PREFLIGHT ────────
# When DOJO_CLOUD=1, source the shared dojo rent/preflight helper and
# run ALL SIX no-troubleshoot fixes (sidecar handoff 4474f21b) BEFORE
# any cost-bearing rental, so the kata rents+launches a multi-GPU DDP
# pod WITHOUT the 2h-of-dead-pods the anima 7B fire suffered:
#   1 image-tag validation · 2 PUBLIC_KEY inject · 3 supply ladder ·
#   4 failure classification · 5 per-GPU mem gate · 6 torchrun harvest.
# Every failure prints a CAUSE + FIX line — never a silent dead pod.
if [ "${DOJO_CLOUD:-0}" = "1" ]; then
    # find the helper by walking up to the repo root (tool/...).
    HELPER=""
    d="$PWD"
    while [ -n "$d" ] && [ "$d" != "/" ]; do
        if [ -f "$d/tool/dojo_rent_preflight.sh" ]; then HELPER="$d/tool/dojo_rent_preflight.sh"; break; fi
        d="$(dirname "$d")"
    done
    if [ -z "$HELPER" ]; then
        echo "✗ flame-forge: tool/dojo_rent_preflight.sh not found (cloud preflight unavailable)" >&2
        echo "  fix: run from inside the hexa-lang repo, or set DOJO_CLOUD=0 for the local CPU gate" >&2
        exit 1
    fi
    # shellcheck source=/dev/null
    source "$HELPER"
    # fix #5 — BLOCK before OOM. Override the spec via env when training a
    # real model (these defaults size the kata itself; a 7B DDP run sets
    # DOJO_PARAMS / DOJO_DTYPE / DOJO_OPT / DOJO_GPU / DOJO_NGPU).
    dojo_preflight_mem \
        --params "${DOJO_PARAMS:-7000000000}" \
        --param-dtype "${DOJO_DTYPE:-fp32}" \
        --optimizer "${DOJO_OPT:-adamw}" \
        --ddp "${DOJO_NGPU:-8}" \
        --gpu "${DOJO_GPU:-h200-141gb}" || {
            echo "✗ flame-forge: preflight BLOCKED the launch (would OOM) — fix the spec above before renting" >&2; exit 1; }
    # fix #1-4 — validate image + inject PUBLIC_KEY + walk the supply
    # ladder + classify; take the first available pod id.
    POD_ID="$(dojo_rent \
        --gpu-type "${DOJO_GPU_TYPE:-NVIDIA H200}" \
        --gpu-count "${DOJO_NGPU:-8}" \
        --image "${DOJO_IMAGE:-runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04}" \
        --name "flame-forge-mlp")" || {
            echo "✗ flame-forge: rent failed — see the cause+fix above (host=ubu-1)" >&2; exit 1; }
    echo "flame-forge: pod $POD_ID up — fix #6 launches torchrun with --tee 3 --redirect 3 --log-dir"
    echo "  launch (on the pod): $(dojo_torchrun_cmd "${DOJO_NGPU:-8}" train_ddp.py)"
    echo "  on ChildFailedError: dojo_harvest_rank_logs   # torchrun hides child errors; the real trace is here"
    exit 0
fi

# ── local CPU path (default) — the descent-gate kata ────────────────
# Run the self-contained flame trainer on this host (CPU farr matmul
# fallback; a forge-GPU host accelerates the SAME code unchanged),
# then assert the descent gate. Machine-independent $0 gate.
RUN_LOG="$PWD/train.$$.log"
echo "flame-forge: hexa run train.hexa"
hexa run train.hexa 2>&1 | tee "$RUN_LOG"

if grep -q "F-FLAMEFORGE-MLP = 1" "$RUN_LOG"; then
    echo "GATE F-FLAMEFORGE-MLP: GREEN (loss descends)"
else
    echo "GATE F-FLAMEFORGE-MLP: RED (no descent)" >&2
    exit 1
fi
